name: Docker Image CI

on:
  push:
    branches: [ "18.0" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout du dépôt actuel
    - name: Checkout repository
      uses: actions/checkout@v4

    # # 2. Télécharger le Dockerfile et les fichiers nécessaires directement dans le répertoire courant
    # - name: Debug Dockerfile dependencies download
    #   run: |
    #     curl -o entrypoint.sh https://raw.githubusercontent.com/odoo/docker/master/18.0/entrypoint.sh
    #     echo "Downloaded entrypoint.sh ✅"
    #     curl -o odoo.conf https://raw.githubusercontent.com/odoo/docker/master/18.0/odoo.conf
    #     echo "Downloaded odoo.conf ✅"
    #     curl -o wait-for-psql.py https://raw.githubusercontent.com/odoo/docker/master/18.0/wait-for-psql.py
    #     echo "Downloaded wait-for-psql.py ✅"
    #     chmod +x entrypoint.sh
    #     echo "Made entrypoint.sh executable ✅"
    #     chmod +x odoo.conf
    #     echo "Made odoo.conf executable ✅"
    #     chmod +x wait-for-psql.py
    #     echo "Made wait-for-psql.py executable ✅"

    # 3. Authentification à Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_ACCOUNT }} 
        password: ${{ secrets.DOCKERHUB_TOKEN }}   

    # 4. Construire l'image Docker
    - name: Build Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag ${{ secrets.DOCKERHUB_ACCOUNT }}/pack-entreprise:latest \
          --tag ${{ secrets.DOCKERHUB_ACCOUNT }}/pack-entreprise:0.1

    # 5. Pousser l'image vers Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_ACCOUNT }}/pack-entreprise:latest
        docker push ${{ secrets.DOCKERHUB_ACCOUNT }}/pack-entreprise:1.0

    # 6. Nettoyer les fichiers temporaires
    # - name: Clean up
    #   run: rm -f Dockerfile entrypoint.sh odoo.conf wait-for-psql.py
