name: Docker Image CI

on:
  push:
    branches: [ "18.0" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout du dépôt actuel
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Télécharger le Dockerfile et les fichiers nécessaires
    - name: Download Dockerfile and dependencies
      run: |
        mkdir -p docker_files
        curl -o docker_files/Dockerfile https://raw.githubusercontent.com/odoo/docker/master/18.0/Dockerfile
        curl -o docker_files/entrypoint.sh https://raw.githubusercontent.com/odoo/docker/master/18.0/entrypoint.sh
        curl -o docker_files/odoo.conf https://raw.githubusercontent.com/odoo/docker/master/18.0/odoo.conf
        curl -o docker_files/wait-for-psql.py https://raw.githubusercontent.com/odoo/docker/master/18.0/wait-for-psql.py

    # 3. Authentification à Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_ACCOUNT }} 
        password: ${{ secrets.DOCKERHUB_TOKEN }}   

    # 4. Construire l'image Docker
    - name: Build Docker image
      run: |
        docker build . \
          --file docker_files/Dockerfile \
          --tag ${{ secrets.DOCKER_USERNAME }}/pack-entreprise-18.0:latest

    # 5. Pousser l'image vers Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/pack-entreprise-18.0:latest

    # 6. Nettoyer les fichiers temporaires
    - name: Clean up
      run: rm -rf docker_files
